### PR TITLE
model update and testing

### PR DESCRIPTION
**Pull request by mmcgurn**
Hi @chandola and @profPlum!  This PR updates the models to work with some changes in ablate.  It also includes automated PR testing for new models.  It does this using GitHub actions/dockers to download ablate, build ablate, build chemtab tests (that use ablate), and runs the tests.  For this to be useful I would highly recommend adding some basic branch protections to this repo.  I've included screenshots of the settings I would recommend. Please let me know if you want me to make any changes or if I can help with anything. 

image
image

### CODE REVIEW

**Comment by profPlum** [comment]
Hey Matt I'm taking a look now. So this just uses the same tests that we've been using thus far but integrates them into GitHub CI?

**Comment by profPlum** [comment]
Sorry didn't mean to close. I'm still looking at it

**Comment by mmcgurn** [comment]
It is an expanded/updated set of tests that test each model in the repo and grabs the latest ablate automatically.

**Review by profPlum — COMMENTED** [review]
In regards to the test from the first commit, that "doesn't work with chemtab currently": how do we make this work with chemtab? Is this related to your comment about predicting Zmix?

**Review by profPlum — CHANGES_REQUESTED** [review]
"ipath" variable no longer makes sense because, we aren't using psuedo inverse any longer (now using neural inverse).

Also are you saying that you want Zmix source to be predicted by the model? The source should always be 0 right? Can't we just manually output 0 or ignore it in source outputs?

If this assumption isn't correct please tell me. But of course we can still include weights to derive Zmix from species inside the weight matrix no problem... (I already have code to do this)

**Comment by mmcgurn** [comment]
> In regards to the test from the first commit, that "doesn't work with chemtab currently": how do we make this work with chemtab? Is this related to your comment about predicting Zmix?

Yes, we need to add predicting zmix

**Comment by mmcgurn** [comment]
> "ipath" variable no longer makes sense because, we aren't using psuedo inverse any longer (now using neural inverse).
> 
> Also are you saying that you want Zmix source to be predicted by the model? The source should always be 0 right? Can't we just manually output 0 or ignore it in source outputs?
> 
> If this assumption isn't correct please tell me. But of course we can still include weights to derive Zmix from species inside the weight matrix no problem... (I already have code to do this)

It is easier from a testing and understanding and future proofing perspective to just treat zMix as any other progress variable and just set the expected source term to zero.  This also makes the call into the model for testing the same as the real one.

This is how we can move forward:
1. merge this PR in as it is because it is the current state of the models that work with ABLATE.  It also includes the required PR testing.
2. Update ablate with the proposed changes along with updating the test model in the ABLATE repo.
3. Update this repo with the new models.  They should all pass the tests with the latest version of ablate.

**Pull request merged**
